# Generated by Django 2.2 on 2019-10-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20191031_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnover',
            name='EducationField',
            field=models.CharField(choices=[('L S', 'Life Sciences'), ('Medical', 'Medical'), ('Marketing', 'Marketing'), ('T D', 'Technical Degree'), ('H R', 'Human Resources'), ('Other', 'Other')], default='Medical', max_length=100),
        ),
        migrations.AddField(
            model_name='turnover',
            name='JobRole',
            field=models.CharField(choices=[('S.E', 'Sales Executive'), ('R.S', 'Research Scientist'), ('L.T', 'Laboratory Technician'), ('M.D', 'Manufacturing Director'), ('H.R', 'Healthcare Representative'), ('Manager', 'Manager'), ('S.P', 'Sales Representative'), ('R.D', 'Research Director'), ('R.D', 'Research Director'), ('H.R', 'Human Resources')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnover',
            name='TotalWorkingYears',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='turnover',
            name='YearsAtCompany',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='turnover',
            name='YearsInCurrentRole',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
